# nixpacks.toml

[phases.setup]
# Install Python 3 and FFmpeg
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
# 1. 'ensurepip' installs pip into the current environment
# 2. Then we install the requirements
cmds = [
    "python3 -m ensurepip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
# Generate the media files
cmds = ["python3 build.py"]

[start]
# Start Gunicorn using the module syntax to ensure path is correct
cmd = "python3 -m gunicorn app:app"